---
# Provisioner for beefy pods
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: beefy
spec:
  template:
    metadata:
      # Only provision nodes for pods specifying the beefy node pool
      labels:
        spack.io/node-pool: beefy

    spec:
      requirements:
      - key: "node.kubernetes.io/instance-type"
        operator: In
        values: ["r5.2xlarge"]

      # Always use on-demand
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: ["on-demand"]

      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default

  # Terminate nodes after 5 minutes of idle time
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 5m
