apiVersion: batch/v1
kind: Job
metadata:
  name: webhook-handler-db-migration
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: ghcr.io/spack/django:0.3.1
          command:
            - python
            - manage.py
            - migrate
